"""initial schema

Revision ID: 67a87d4beb2d
Revises: 
Create Date: 2026-07-16 22:47:35.347358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a87d4beb2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.Column('donations', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('clan_joined_at', sa.DateTime(), nullable=True),
    sa.Column('contribution_score', sa.Float(), nullable=True),
    sa.Column('contribution_score_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('war_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id'),
    sa.UniqueConstraint('start_date')
    )
    op.create_table('contribution_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tag', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('war_activity', sa.Float(), nullable=False),
    sa.Column('war_performance', sa.Float(), nullable=False),
    sa.Column('donations', sa.Float(), nullable=False),
    sa.Column('trophy_level', sa.Float(), nullable=False),
    sa.Column('activity', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('seniority', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('river_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['war_seasons.season_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'section_index', name='uq_river_race')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tag', sa.String(), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.Column('donations', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('war_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tag', sa.String(), nullable=False),
    sa.Column('river_race_id', sa.Integer(), nullable=False),
    sa.Column('fame', sa.Integer(), nullable=False),
    sa.Column('repair_points', sa.Integer(), nullable=False),
    sa.Column('boat_attacks', sa.Integer(), nullable=False),
    sa.Column('decks_used', sa.Integer(), nullable=False),
    sa.Column('decks_used_today', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.ForeignKeyConstraint(['river_race_id'], ['river_races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('river_race_id', 'member_tag', name='uq_race_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('war_participation')
    op.drop_table('snapshots')
    op.drop_table('river_races')
    op.drop_table('contribution_scores')
    op.drop_table('war_seasons')
    op.drop_table('members')
    # ### end Alembic commands ###
