"""initial schema

Revision ID: 75322d62dbd9
Revises: 
Create Date: 2026-06-06 21:32:19.514662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75322d62dbd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.Column('donations', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('promotion_score', sa.Float(), nullable=True),
    sa.Column('promotion_score_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('war_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id')
    )
    op.create_table('promotion_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tag', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('war_activity', sa.Float(), nullable=False),
    sa.Column('war_win_rate', sa.Float(), nullable=False),
    sa.Column('donations', sa.Float(), nullable=False),
    sa.Column('trophy_level', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tag', sa.String(), nullable=False),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.Column('donations', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('war_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tag', sa.String(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('attacks_used', sa.Integer(), nullable=False),
    sa.Column('attacks_possible', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('medals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.ForeignKeyConstraint(['season_id'], ['war_seasons.season_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('war_participations')
    op.drop_table('snapshots')
    op.drop_table('promotion_scores')
    op.drop_table('war_seasons')
    op.drop_table('members')
    # ### end Alembic commands ###
