"""add river race support

Revision ID: 98f79a5781b4
Revises: 75322d62dbd9
Create Date: 2026-06-17 20:33:31.479033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f79a5781b4'
down_revision: Union[str, Sequence[str], None] = '75322d62dbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('river_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['war_seasons.season_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'section_index', name='uq_river_race')
    )
    op.create_table('war_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_tag', sa.String(), nullable=False),
    sa.Column('river_race_id', sa.Integer(), nullable=False),
    sa.Column('fame', sa.Integer(), nullable=False),
    sa.Column('repair_points', sa.Integer(), nullable=False),
    sa.Column('boat_attacks', sa.Integer(), nullable=False),
    sa.Column('decks_used', sa.Integer(), nullable=False),
    sa.Column('decks_used_today', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.ForeignKeyConstraint(['river_race_id'], ['river_races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('river_race_id', 'member_tag', name='uq_race_member')
    )
    op.drop_table('war_participations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_participations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_tag', sa.VARCHAR(), nullable=False),
    sa.Column('season_id', sa.VARCHAR(), nullable=False),
    sa.Column('attacks_used', sa.INTEGER(), nullable=False),
    sa.Column('attacks_possible', sa.INTEGER(), nullable=False),
    sa.Column('wins', sa.INTEGER(), nullable=False),
    sa.Column('losses', sa.INTEGER(), nullable=False),
    sa.Column('medals', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['member_tag'], ['members.tag'], ),
    sa.ForeignKeyConstraint(['season_id'], ['war_seasons.season_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('war_participation')
    op.drop_table('river_races')
    # ### end Alembic commands ###
